version: "3.9"

services:
  smartcam-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: smartcam-server
    ports:
      - "7777:7777"
    restart: unless-stopped


